FROM python:3.9

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir requests[socks]
RUN pip install --no-cache-dir jsonify

CMD ["python", "server.py"]

